server:
  port: 80

spring:
  application:
    name: web-base
  #  mvc:
  #    static-path-pattern: /static/**
  freemarker:
    template-loader-path: classpath:/webapps/templates/
    suffix: .html
    cache: false
  servlet:
    multipart:
      max-file-size: 50Mb
      max-request-size: 100Mb
  http:
    encoding:
      charset: UTF-8
  resources:
    static-locations: classpath:/webapps/static/

###### redis ######
spring.redis:
  host: 192.168.35.105  # Redis数据库索引（默认为0）
  port: 16379           # Redis服务器地址
  database: 0           # Redis服务器连接端口
  password: 37621040    #Redis服务器连接密码（默认为空）
  jedis:
    pool:
      max-active: 8     # 连接池中的最大空闲连接
      max-wait: 3000ms  # 连接池中的最小空闲连接
      max-idle: 8       # 连接池最大连接数（使用负值表示没有限制）
      min-idle: 0       # 连接池最大阻塞等待时间（使用负值表示没有限制）
  timeout: 3000ms       # 连接超时时间（毫秒）















