
server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8

spring:
  application:
    name: web-base
#  mvc:
#    static-path-pattern: /static/**
  freemarker:
    template-loader-path: classpath:/webapps/templates/
    suffix: .html
    cache: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  resources:
    static-locations: classpath:/webapps/static/

















